# edge node 4 consumes assigments from broker                                                                                                                                                              
                                                                                                                                                                                                           
from kafka import KafkaConsumer, KafkaProducer                                                                                                                                                             
import sys                                                                                                                                                                                                 
import os                                                                                                                                                                                                  
import jsons                                                                                                                                                                                               
from json import loads                                                                                                                                                                                     
import threading                                                                                                                                                                                           
#from queue import Queue                                                                                                                                                                                   
#from confluent_kafka.avro import AvroConsumer                                                                                                                                                             
                                                                                                                                                                                                           
                                                                                                                                                                                                           
sys.path.insert(1, '/home/syslab/workspace_la/edge_nodes/tasks/')                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                           
bootstrap_servers = ['ip_add']                                                                                                                                                                 
assignmentTopic = ['assignments']                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                           
def processMSG(msg):                                                                                                                                                                                                                                                                                                                                                                         
    print("Start task...")                                                                                                                                                                                 
    assignment = msg                                                                                                                                                                                       
    if assignment == 1:                                                                                                                                                                                    
        print("Running task1...")                                                                                                                                                                          
        os.system('python3 /home/syslab/workspace_la/edge_nodes/tasks/task1.py')                                                                                                                           
    elif assignment == 2:                                                                                                                                                                                  
        print("Running task2...")                                                                                                                                                                          
        os.system('python3 /home/syslab/workspace_la/edge_nodes/tasks/task2.py')                                                                                                                           
    else:                                                                                                                                                                                                  
        print("Running task3...")                                                                                                                                                                          
        os.system('python3 /home/syslab/workspace_la/edge_nodes/tasks/task3.py')                                                                                                                           
                                                                                                                                                                                                           
                                                                                                                                                                                                           
def consume():                                                                                                                                                                                                                                                                                                                                                         
    consumer4 = KafkaConsumer(client_id='edge node 4', bootstrap_servers = bootstrap_servers, auto_offset_reset = 'latest', value_deserializer=lambda x: loads(x.decode('utf-8')))                         
    consumer4.subscribe(topics=assignmentTopic)                                                                                                                                                            
    while True:                                                                                                                                                                                            
        print("Waiting for assignments...")                                                                                                                                                                
        records = consumer4.poll(timeout_ms=10000)                                                                                                                                                         
        #processMSG(avroMSG)                                                                                                                                                                               
        for _, consumer_records in records.items():                                                                                                                                                        
            for consumer_record in consumer_records:                                                                                                                                                       
                print(consumer_record.value)                                                                                                                                                               
                value = consumer_record.value                                                                                                                                                              
                #Queueq.put(value)                                                                                                                                                                         
                #print("Add mess to queue...")                                                                                                                                                             
                #work = Queueq.get()                                                                                                                                                                       
                #print("work now is ", work)                                                                                                                                                               
                msg = value['4']                                                                                                                                                                           
                print("assignment is ", msg)                                                                                                                                                               
                t = threading.Thread(target=processMSG, args=(msg,))                                                                                                                                                       t.daemon = True                                                                                                                                                                            
                t.start()                                                                                                                                                                                  
                                                                                                                                                                                                           #edgeNode4 = KafkaConsumer(client_id='edge node 4', bootstrap_servers = bootstrap_servers, auto_offset_reset = 'latest', value_deserializer=lambda x: loads(x.decode('utf-8')))                            
consume()                                                                                                                                                                                      
  
